apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: sotolito-nginx
spec:
  containers:
  - name: sotolito-nginx-container
    image: hub.sotolitolabs.com:5000/sotolitolabs-alpine-arm-nginx-setup
    command: ["nginx", "-g", "daemon off;"]
    ports:
    - containerPort: 80
      hostPort: 8080
      name: sotolito-nginx-container-port
    volumeMounts:
    - name: stolito-nginx-var-volume
      mountPath: /var
    - name: sotolito-nginx-etc-volume
      mountPath: /etc/nginx
    - name: sotolito-nginx-php-fpm-volume
      mountPath: /run/php-fpm
    - name: sotolito-nginx-php-apps
      mountPath: /var/lib/nginx/html/php-apps
  volumes:
  - name: stolito-nginx-var-volume
    hostPath:
      path: /var/sotolito/vols/nginx/var
      # Create it if does not exist
      type: DirectoryOrCreate
  - name: sotolito-nginx-etc-volume
    hostPath:
      path: /var/sotolito/vols/nginx/etc/nginx
      type: DirectoryOrCreate
  - name: sotolito-nginx-php-fpm-volume
    hostPath:
      path: /var/sotolito/vols/php-fpm/run/php-fpm/
      type: DirectoryOrCreate
  - name: sotolito-nginx-php-apps
    hostPath:
      path: /var/sotolito/vols/php-apps
      type: DirectoryOrCreate
  initContainers:
  - name: sotolito-init-nginx-container
    image: hub.sotolitolabs.com:5000/sotolitolabs-alpine-arm-nginx-setup
    command: ['/setup.sh']
    volumeMounts:
    - name: stolito-nginx-setup-var-volume
      mountPath: /var/sotolito
  volumes:
  - name: stolito-nginx-setup-var-volume
    hostPath:
      path: /var/sotolito
      type: DirectoryOrCreate


